pip install numpy

In [1]:
import numpy as np

In [3]:
list_of_num = [1,2,3,4,5]

In [17]:
len(list_of_num)

5

In [19]:
list_of_num.shape

AttributeError: 'list' object has no attribute 'shape'

In [4]:
type(list_of_num)

list

In [6]:
type(list_of_num[0])

int

In [7]:
array_of_num = np.array(list_of_num)

In [27]:
array_of_num.shape

(5,)

In [9]:
type(array_of_num)

numpy.ndarray

In [10]:
type(array_of_num[0])

numpy.int32

In [12]:
array_of_num.dtype

dtype('int32')

In [13]:
list_of_list_of_num = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [14]:
type(list_of_list_of_num)

list

In [21]:
len(list_of_list_of_num), len(list_of_list_of_num[0])

(3, 3)

In [20]:
list_of_list_of_num.shape

AttributeError: 'list' object has no attribute 'shape'

In [15]:
list_of_list_of_num[0][1]

2

In [16]:
list_of_list_of_num

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [22]:
array_of_list_of_num = np.array(list_of_list_of_num)

In [25]:
array_of_list_of_num.shape

(3, 3)

In [26]:
len(array_of_list_of_num)

3

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.ones((3,3)).dtype

dtype('float64')

In [98]:
np.ones((3,3)).astype(int).dtype

dtype('int32')

In [99]:
np.ones((3,3)).astype(np.int64).dtype

dtype('int64')

In [101]:
np.ones((3,3)).astype(np.int32).dtype    # or int8

dtype('int32')

In [31]:
np.twos((3,3))

AttributeError: module 'numpy' has no attribute 'twos'

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
eye_3 = np.eye(3)
eye_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
eye_3[0][0]

1.0

In [35]:
eye_3[0,0]

1.0

In [37]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [38]:
eye_3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
np.diag([1,2,3])*eye_3

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [40]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
np.arange(-5,20)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,
       12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
np.arange(1,20,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [45]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [43]:
list(range(1,20,2))

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [47]:
np.arange(1,5,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [51]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [52]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [55]:
diag_4 = np.diag([1,2,3,4])
diag_4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

result getting row and column wise as your query

In [60]:
diag_4[1:, 1:]    #slice- remove upto 1st row and upto 1st column

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 4]])

In [62]:
diag_4[2:, 2:]    #slice- remove upto 2st row and upto 2st column

array([[3, 0],
       [0, 4]])

In [63]:
diag_4[:2, 2:]    #slice- remove nextto 2st row and upto 2st column

array([[0, 0],
       [0, 0]])

In [64]:
diag_4[:3, :2]    #slice- remove nextto 3st row and next to 2st column

array([[1, 0],
       [0, 2],
       [0, 0]])

In [67]:
diag_4

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

result getting row wise , not column wise query their 

In [65]:
diag_4[: 2:]    # slice - [start : stop : step] - default [0:0:1]

array([[1, 0, 0, 0],
       [0, 2, 0, 0]])

In [68]:
diag_4[1: :] 

array([[0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [69]:
diag_4[1: :2] 

array([[0, 2, 0, 0],
       [0, 0, 0, 4]])

In [70]:
diag_4[1:2:2] 

array([[0, 2, 0, 0]])

In [71]:
diag_4_list= diag_4[:2, 2:]
diag_4_list

array([[0, 0],
       [0, 0]])

In [87]:
arr = np.arange(-5,20,0.5)
arr

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5,
       17. , 17.5, 18. , 18.5, 19. , 19.5])

In [88]:
arr.shape

(50,)

In [89]:
arr = arr.reshape(10,-1)
arr

array([[-5. , -4.5, -4. , -3.5, -3. ],
       [-2.5, -2. , -1.5, -1. , -0.5],
       [ 0. ,  0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ],
       [ 7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. ],
       [12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. ],
       [17.5, 18. , 18.5, 19. , 19.5]])

In [90]:
arr.shape

(10, 5)

In [91]:
arr = arr.reshape(-1)
arr

array([-5. , -4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,
        0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,
        6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5, 11. ,
       11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5,
       17. , 17.5, 18. , 18.5, 19. , 19.5])

In [92]:
arr.shape

(50,)

In [94]:
arr = arr.reshape(10,-1)
arr.shape

(10, 5)

In [96]:
arr = arr.flatten()
arr.shape

(50,)

In [102]:
arr1 = np.arange(5,15)
arr2 = np.arange(15,25)

In [103]:
arr1.shape

(10,)

In [104]:
arr2.shape

(10,)

In [110]:
arr1 = arr1.reshape(5,-1)

In [111]:
arr2 = arr2.reshape(5,-1)

In [112]:
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [113]:
arr2

array([[15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [114]:
arr1+arr2

array([[20, 22],
       [24, 26],
       [28, 30],
       [32, 34],
       [36, 38]])

In [115]:
arr1-arr2

array([[-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10],
       [-10, -10]])

In [116]:
arr1*arr2

array([[ 75,  96],
       [119, 144],
       [171, 200],
       [231, 264],
       [299, 336]])

In [117]:
arr1/arr2

array([[0.33333333, 0.375     ],
       [0.41176471, 0.44444444],
       [0.47368421, 0.5       ],
       [0.52380952, 0.54545455],
       [0.56521739, 0.58333333]])

This all operation works well becuase the size of both array is same

In [118]:
arr1 < arr2

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

In [119]:
arr1 > arr2

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False]])

In [120]:
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [121]:
arr1 > 10

array([[False, False],
       [False, False],
       [False, False],
       [ True,  True],
       [ True,  True]])

In [125]:
arr1[arr1 > 10]

array([11, 12, 13, 14])

In [126]:
(arr1 > 8) & (arr1 < 13)

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [128]:
np.logical_and((arr1 > 8) , (arr1 < 13))

array([[False, False],
       [False, False],
       [ True,  True],
       [ True,  True],
       [False, False]])

In [127]:
arr1[(arr1 > 8) & (arr1 < 13)]

array([ 9, 10, 11, 12])

In [129]:
arr1[np.logical_and((arr1 > 8) , (arr1 < 13))]

array([ 9, 10, 11, 12])

In [130]:
arr1.mean()

9.5

In [131]:
arr1.sum()

95

In [132]:
arr1.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [133]:
np.median(arr1)

9.5

In [135]:
arr1.sort()
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [136]:
np.std(arr1)

2.8722813232690143

In [137]:
np.average(arr1)

9.5

In [140]:
np.corrcoef(arr1,arr2)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [141]:
np.random.rand(3,2)

array([[0.62152753, 0.86215566],
       [0.26560162, 0.20173527],
       [0.97964486, 0.97159046]])

In [142]:
arr1

array([[ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [145]:
arr2 = arr2.reshape(2,5)

In [146]:
arr2

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [148]:
np.dot(arr1,arr2)     #multiplication

array([[195, 206, 217, 228, 239],
       [265, 280, 295, 310, 325],
       [335, 354, 373, 392, 411],
       [405, 428, 451, 474, 497],
       [475, 502, 529, 556, 583]])

In [150]:
arr1 * arr2          #multiplication but only on (5,2) and (5,2)

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [151]:
arr2 = arr2.reshape(5,2)

In [152]:
arr1 * arr2          #multiplication but only on (5,2) and (5,2)

array([[ 75,  96],
       [119, 144],
       [171, 200],
       [231, 264],
       [299, 336]])